"""empty message

Revision ID: cd14638b281d
Revises: 
Create Date: 2023-05-22 14:40:03.439321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd14638b281d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('bed_no', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('bath_no', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('street', sa.String(length=256), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('surname', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('address1', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('address2', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('county', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('profile_pic',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=250),
               existing_nullable=True)
        batch_op.alter_column('pic_file_path',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('pic_file_path',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('profile_pic',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('date_joined')
        batch_op.drop_column('area')
        batch_op.drop_column('county')
        batch_op.drop_column('address2')
        batch_op.drop_column('address1')
        batch_op.drop_column('phone')
        batch_op.drop_column('surname')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('street')
        batch_op.drop_column('county')
        batch_op.drop_column('bath_no')
        batch_op.drop_column('bed_no')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
